//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TentRentalProject.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionHistory()
        {
            this.TransactionHistory1 = new HashSet<TransactionHistory>();
        }
    
        public int TransactionID { get; set; }
        public int ProductID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<System.DateTime> TransactionDateTime { get; set; }
        public string TransactionType { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> TransactionParentID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionHistory> TransactionHistory1 { get; set; }
        public virtual TransactionHistory TransactionHistory2 { get; set; }
    }
}
